name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install
          npm audit fix

  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build . -t bank-app

      - name: Tag and Push Docker Image
        run: |
          docker tag bank-app:${{ github.sha }} kennedyuche/bank-app:${{ github.sha }}
          docker push kennedyuche/bank-app:${{ github.sha }}

      - name: Send Slack Notification on Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{'text':'Workflow succeeded!'}" $SLACK_WEBHOOK
      - name: Send Slack Notification on Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{'text':'Workflow failed!'}" $SLACK_WEBHOOK